import { getSession } from "@/appwrite/getSession";
import { getUserDocument } from "@/appwrite/getUserDocument";
import { Header } from "@/components/navigation/header";
import { Footer } from "@/components/landing/footer";
import { COMPANY } from "@/lib/company";

export const metadata = {
  title: `Terms of Service - ${COMPANY.name}`,
  description: `Terms of Service for ${COMPANY.name}.`,
};

export default async function TermsPage() {
  const session = await getSession();
  let userDoc = null;
  if (session) userDoc = await getUserDocument(session.id);

  return (
    <div>
      <Header session={session} userDoc={userDoc} />
      <main className="max-w-3xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: January 1, {COMPANY.copyrightYear}</p>

        <div className="space-y-10 text-sm leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-lg font-semibold">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground">
              By accessing or using {COMPANY.name} (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Service. {COMPANY.legalName} (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) reserves the right to update these terms at any time. Continued use of the Service after changes are posted constitutes acceptance of the revised terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">2. Description of Service</h2>
            <p className="text-muted-foreground">
              {COMPANY.name} is an AI-powered vehicle damage assessment platform that allows users to submit video or photographic evidence of vehicle damage and receive automated analysis including damage identification, repair cost estimates, and coverage assessments. The Service is intended to assist with insurance claim preparation and is not a substitute for a professional appraisal or insurance adjuster review.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">3. User Accounts</h2>
            <p className="text-muted-foreground">
              You may create an account using your email address or by signing in with Google OAuth2. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must promptly notify us of any unauthorized use of your account at{" "}
              <a href={`mailto:${COMPANY.supportEmail}`} className="text-primary underline underline-offset-4">
                {COMPANY.supportEmail}
              </a>.
            </p>
            <p className="text-muted-foreground">
              You must be at least 18 years old to create an account and use the Service. By creating an account, you represent that you meet this requirement.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">4. Acceptable Use</h2>
            <p className="text-muted-foreground">
              You agree to use the Service only for lawful purposes and in accordance with these Terms. You must not:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
              <li>Submit false, misleading, or fraudulent information or media</li>
              <li>Attempt to manipulate AI assessments through deceptive inputs</li>
              <li>Use the Service to support fraudulent insurance claims</li>
              <li>Reverse-engineer, scrape, or otherwise extract data from the Service without permission</li>
              <li>Violate any applicable local, national, or international laws or regulations</li>
              <li>Interfere with or disrupt the integrity or performance of the Service</li>
            </ul>
            <p className="text-muted-foreground">
              We reserve the right to suspend or terminate accounts that violate these terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">5. AI-Generated Content Disclaimer</h2>
            <p className="text-muted-foreground">
              All damage assessments, repair cost estimates, fraud risk scores, and coverage analyses generated by {COMPANY.name} are produced by artificial intelligence and are provided for informational purposes only. These outputs:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
              <li>Do not constitute professional insurance advice, legal advice, or a formal appraisal</li>
              <li>May contain errors, omissions, or inaccuracies</li>
              <li>Should not be relied upon as the sole basis for insurance claim decisions</li>
            </ul>
            <p className="text-muted-foreground">
              Always consult a licensed insurance professional for authoritative claim assessments. {COMPANY.name} is not liable for decisions made based on AI-generated content.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">6. Limitation of Liability</h2>
            <p className="text-muted-foreground">
              To the maximum extent permitted by applicable law, {COMPANY.legalName} shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or goodwill, arising out of or in connection with your use of the Service, even if we have been advised of the possibility of such damages.
            </p>
            <p className="text-muted-foreground">
              Our total liability to you for any claims arising under these Terms shall not exceed the amount you paid to us in the twelve (12) months preceding the claim.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">7. Changes to Terms</h2>
            <p className="text-muted-foreground">
              We may update these Terms of Service from time to time. When we make material changes, we will update the &quot;Last updated&quot; date at the top of this page. We encourage you to review these Terms periodically. Your continued use of the Service after any changes constitutes your acceptance of the new terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">8. Contact</h2>
            <p className="text-muted-foreground">
              If you have questions about these Terms of Service, please contact us:
            </p>
            <address className="not-italic text-muted-foreground space-y-1">
              <p><strong>{COMPANY.legalName}</strong></p>
              {COMPANY.address.split("\n").map((line, i) => (
                <p key={i}>{line}</p>
              ))}
              <p>
                Email:{" "}
                <a href={`mailto:${COMPANY.email}`} className="text-primary underline underline-offset-4">
                  {COMPANY.email}
                </a>
              </p>
            </address>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
